// Code generated by sqlc. DO NOT EDIT.

package meetingDb

import (
	"database/sql"
	"time"

	"GeekMeeting/internal/sqltime"
)

// 参会记录
type Recond struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// 会议昵称
	Name sql.NullString `json:"name"`
	// 会议ID
	RoomID int64 `json:"room_id"`
}

// 会议房间
type Room struct {
	ID        int64            `json:"id"`
	StartTime sqltime.NullTime `json:"start_time"`
	EndTime   sqltime.NullTime `json:"end_time"`
	// 会议密码
	Password   string           `json:"password"`
	MasterID   int64            `json:"master_id"`
	CreateTime sqltime.NullTime `json:"create_time"`
	// 不做任何功能，用于查询结果添加字段
	Expand string `json:"expand"`
}

type User struct {
	ID int64 `json:"id"`
	// 邮箱
	Email      string    `json:"email"`
	CreateTime time.Time `json:"create_time"`
}
